name = "tally"
main = "build/worker/shim.mjs"
compatibility_date = "2026-05-13"
compatibility_flags = ["http_request_timeout"]

[[durable_objects.bindings]]
name = "TALLY_TEAM_DO"
class_name = "TallyTeamDO"
script_name = "tally"

[[migrations]]
tag = "v1"
new_classes = ["TallyTeamDO"]

[build]
command = "cargo install -q worker-build && worker-build --release"
